import glob
import os
import sys
from typing import List

import converter


def main(args: List[str]) -> int:
    if len(args) != 3:
        print(f"Usage: {args[0]} input output_dir")
        return 1
    try:
        if not os.path.exists(args[2]):
            os.makedirs(args[2])
    except PermissionError as err:
        print(err, file=sys.stderr)
        return 1
    try:
        if os.path.isdir(args[1]):
            converter.convert(glob.glob(f"{args[1]}/*.json"), args[2])
        else:
            converter.convert(args[1], args[2])
    except converter.ConversionError as err:
        print(err, file=sys.stderr)
        return 1
    return 0


def entrypoint() -> None:
    """This is needed for the script generated by setuptools."""
    sys.exit(main(sys.argv))


if __name__ == "__main__":
    entrypoint()
